#!/bin/bash

cd /app/src

export CI=true

# Copy HEAD test files from /tests (overwrites BASE state)
mkdir -p "test/spec/Feature/OpenApi"
cp "/tests/spec/Feature/OpenApi/OpenApiSpec.hs" "test/spec/Feature/OpenApi/OpenApiSpec.hs"
mkdir -p "test/spec/fixtures"
cp "/tests/spec/fixtures/schema.sql" "test/spec/fixtures/schema.sql"

test_status=0

echo "Verifying fix for customizable OpenAPI title (PR #2624)..."
echo ""
echo "NOTE: This PR adds support for customizable OpenAPI title and description via schema comments"
echo "HEAD (fixed) should have title/description parsing logic and test"
echo "BASE (buggy) has hardcoded 'PostgREST API' title and no customization"
echo ""

# Check OpenAPI.hs - HEAD should use fromMaybe with dTitle and dDesc variables
echo "Checking src/PostgREST/Response/OpenAPI.hs has customizable title/description..."
if grep -q "fromMaybe \"PostgREST API\" dTitle" "src/PostgREST/Response/OpenAPI.hs" && grep -q "fromMaybe \"This is a dynamic API generated by PostgREST\" dDesc" "src/PostgREST/Response/OpenAPI.hs"; then
    echo "✓ OpenAPI.hs has customizable title and description"
else
    echo "✗ OpenAPI.hs has hardcoded title/description - fix not applied"
    test_status=1
fi

# Check OpenAPI.hs - HEAD should have breakOn logic to split title and description
echo "Checking src/PostgREST/Response/OpenAPI.hs has title/description parsing logic..."
if grep -q "T.breakOn" "src/PostgREST/Response/OpenAPI.hs" && grep -q "dTitle.*dDesc" "src/PostgREST/Response/OpenAPI.hs"; then
    echo "✓ OpenAPI.hs has title/description parsing logic"
else
    echo "✗ OpenAPI.hs missing parsing logic - fix not applied"
    test_status=1
fi

# Check OpenApiSpec.hs - HEAD should have test for title and description
echo "Checking test/spec/Feature/OpenApi/OpenApiSpec.hs has test for custom title/description..."
if grep -q "includes title and comments to schema" "test/spec/Feature/OpenApi/OpenApiSpec.hs" && grep -q "My API title" "test/spec/Feature/OpenApi/OpenApiSpec.hs"; then
    echo "✓ OpenApiSpec.hs has test for customizable title/description"
else
    echo "✗ OpenApiSpec.hs missing test - fix not applied"
    test_status=1
fi

# Check schema.sql - HEAD should have COMMENT ON SCHEMA test with title and description
echo "Checking test/spec/fixtures/schema.sql has schema comment with title/description..."
if grep -q "COMMENT ON SCHEMA test IS" "test/spec/fixtures/schema.sql" && grep -q "My API title" "test/spec/fixtures/schema.sql" && grep -q "My API description" "test/spec/fixtures/schema.sql"; then
    echo "✓ schema.sql has schema comment with title and description"
else
    echo "✗ schema.sql missing schema comment - fix not applied"
    test_status=1
fi

# Check CHANGELOG - HEAD should mention the fix for #1100
echo "Checking CHANGELOG.md mentions customizable OpenAPI title..."
if grep -q "#1100" "CHANGELOG.md" && grep -q "Customizable OpenAPI title" "CHANGELOG.md"; then
    echo "✓ CHANGELOG.md mentions the fix"
else
    echo "✗ CHANGELOG.md does not mention the fix - fix not applied"
    test_status=1
fi

echo ""
if [ $test_status -eq 0 ]; then
    echo "✓ All checks passed - customizable OpenAPI title properly implemented"
    echo 1 > /logs/verifier/reward.txt
else
    echo "✗ Some checks failed - fix not fully applied"
    echo 0 > /logs/verifier/reward.txt
fi
exit "$test_status"
